fstype_name: ext4

device_name_1: /dev/nvme1n1p1
device_name_2: /dev/nvme1n1p2
device_name_3: /dev/nvme1n1p3
device_name_4: /dev/nvme1n1p4

path_for_device_1_mount: /abinitio/apps
path_for_device_2_mount: /abinitio/mfs
path_for_device_3_mount: /abinitio/data
path_for_device_4_mount: /optware

