# Create partitions with parted module

 - name: Creating log file for partitions creation
   become: no
   file:
    dest: /tmp/ansible_logs/logs_partitions.txt
    state: touch
   delegate_to: localhost

 - name: Checking Partition Exits or not
   ignore_errors: False
   become: yes
   become_method: su
   shell: df
   register : partition_exit 

 
 - name: Create a new primary partition with a size of 200GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_first_partition }}'
     number: 1
     state: present
     part_start: 1GB
     part_end: 201GB
     part_type: primary
   when: partition_exit is failed 

 - name: Create a new extended partition with a size of 100GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_second_partition }}'
     number: 2
     state: present
     part_start: 201GB
     part_end: 301GB
     part_type: extended
   when: partition_exit is failed 

 - name: Create a new extended partition with a size of 300GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_third_partition }}'
     number: 3
     state: present
     part_start: 301GB
     part_end: 601GB
     part_type: extended
   when: partition_exit is failed

 - name: Create a new extended partition with a size of 300GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_fourth_partition }}'
     number: 4
     state: present
     part_start: 601GB
     part_end: 901GB
     part_type: extended
   when: partition_exit is failed

 - name: Updating log file preinstalltion task of Co-opearting System when partiotn is already exists
   become: no
   lineinfile:
    dest: /tmp/ansible_logs/logs_partitions.txt
    state: present 
    line: '  - Partition Creation on the server has been Skipped as the Partitotn is already Exists.'
   delegate_to: localhost
   when: partition_exit is success

 - name: Updating log file preinstalltion task of Co-opearting System
   become: no
   lineinfile:
    dest: /tmp/ansible_logs/logs_partitions.txt
    state: present 
    line: '  - Partition Creation on the server has been Completed.'
   delegate_to: localhost
   when: partition_exit is failed
