# Create partitions with parted module

 - name: Creating log file for preinstalltion task of Co-opearting System
   become: no
   file:
    dest: /tmp/ansible_logs/logs_create_partition.txt
    state: touch
   delegate_to: localhost

 - name: Checking Partition Exits or not
   ignore_errors: False
   become: yes
   become_method: su
   shell: df
   register : partition_exist 

 
 - name: Create a new primary partition with a size of 50GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_first_partition }}'
     number: 1
     state: present
     part_start: 1GB
     part_end: 51GB
     part_type: primary
   when: partition_exist is failed 

 - name: Create a new extended partition with a size of 400GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_second_partition }}'
     number: 2
     state: present
     part_start: 51GB
     part_end: 451GB
     part_type: extended
   when: partition_exist is failed 

 - name: Create a new extended partition with a size of 800GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_third_partition }}'
     number: 3
     state: present
     part_start: 451GB
     part_end: 1251GB
     part_type: extended
   when: partition_exist is failed

 - name: Create a new extended partition with a size of 800GB
   parted:
     device: '{{ device_name }}'
     label: '{{ label_name }}'
     name: '{{ name_of_fourth_partition }}'
     number: 4
     state: present
     part_start: 1251GB
     part_end: 2051GB
     part_type: extended
   when: partition_exist is failed

 - name: Updating log file preinstalltion task of Co-opearting System when partiotn is already exists
   become: no
   lineinfile:
    dest: /tmp//tmp/ansible_logs/logs_create_partition.txt.txt 
    line: '  - Partition Creation on the server has been Skipped as the Partitotn is already Exists.\n'
   delegate_to: localhost
   when: partition_exist is success

 - name: Updating log file preinstalltion task of Co-opearting System
   become: no
   lineinfile:
    dest: /tmp/ansible_logs/logs_create_partition.txt.txt 
    line: '  - Partition Creation on the server has been Completed\n'
   delegate_to: localhost
   when: partition_exist is failed
